import { afterEach, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initializeLedger, openLedger } from "./oh-ledger.mjs";
import { canonicalJson } from "@hraness/oh";
import { editionReport, recordExtractionCost } from "./oh-experiment-records.mjs";
import { EXTRACTION_PROTOCOL_SHA256, validateExtractionCost } from "./oh-extraction-report.mjs";

const roots = [];
const reportBytes = readFileSync(new URL("../artifacts/extraction-cost.json", import.meta.url));
const protocolBytes = readFileSync(new URL("../experiments/extraction-cost-protocol.md", import.meta.url));
const report = () => JSON.parse(reportBytes);
function root() {
  const path = mkdtempSync(join(tmpdir(), "peqnp-extraction-ledger-test-"));
  roots.push(path);
  for (const directory of ["artifacts", "experiments", "src"]) mkdirSync(join(path, directory));
  for (const file of ["Cargo.toml", "Cargo.lock", "rust-toolchain.toml"]) writeFileSync(join(path, file), "# synthetic source fixture\n");
  writeFileSync(join(path, "src/lib.rs"), "// Synthetic source fixture, not experimental provenance.\n");
  writeFileSync(join(path, "artifacts/extraction-cost.json"), reportBytes);
  writeFileSync(join(path, "experiments/extraction-cost-protocol.md"), protocolBytes);
  return path;
}
afterEach(() => { for (const path of roots.splice(0)) rmSync(path, { recursive: true, force: true }); });
const find = (actual, predicate) => actual.observations.find(predicate);
const withClues = actual => find(actual, row => row.per_literal.clues.length > 1 && !row.secondary);
const withPaths = actual => find(actual, row => row.settled.certificate?.kind === "opposite-paths");
const unsat = actual => find(actual, row => !row.reference.sat);
const sat = actual => find(actual, row => row.reference.sat);
const satWithClues = actual => find(actual, row => row.reference.sat && row.settled.clues.length > 0);
const mixed = actual => find(actual, row => row.family === "random-mixed" && row.settled.certificate?.kind === "sat");
const fragmentOnly = actual => find(actual, row => row.family === "fragment-only");
const ladder = actual => find(actual, row => row.family === "ladder-control");
const v1Mixed = actual => find(actual, row => row.family === "v1:random-mixed");
const v1Ternary = actual => find(actual, row => row.family === "v1:random-ternary-only");
const v1Chain = actual => find(actual, row => row.family === "v1:chain-embedded");
const v1Contradictory = actual => find(actual, row => row.family === "v1:contradictory-fragment");
const withStats = actual => find(actual, row => row.settled_stats !== null && row.settled_stats.searches > 0);

test("extraction report preserves the fixed corpus and rejects proof, protocol, and corpus changes", () => {
  const actual = report();
  expect(actual.protocol_sha256).toBe(EXTRACTION_PROTOCOL_SHA256);
  expect(actual.observations.length).toBe(338);
  expect(validateExtractionCost(actual)).toBe(actual);
  const proof = report();
  proof.proof_status = "proved-generally";
  expect(() => validateExtractionCost(proof)).toThrow("without a formal-proof");
  const protocol = report();
  protocol.protocol_sha256 = "0".repeat(64);
  expect(() => validateExtractionCost(protocol)).toThrow("without a formal-proof");
  const budget = report();
  budget.arm_budget = 2_000_000;
  expect(() => validateExtractionCost(budget)).toThrow("shared arm budget");
  const missing = report();
  missing.observations.pop();
  expect(() => validateExtractionCost(missing)).toThrow("every fixed extraction-cost case");
  const duplicate = report();
  duplicate.observations[1] = duplicate.observations[0];
  expect(() => validateExtractionCost(duplicate)).toThrow("duplicate");
  const renamed = report();
  mixed(renamed).density = 6;
  expect(() => validateExtractionCost(renamed)).toThrow("fixed corpus");
  const seed = report();
  mixed(seed).effective_seed = "1";
  expect(() => validateExtractionCost(seed)).toThrow("fixed corpus");
  const section = report();
  mixed(section).secondary = true;
  expect(() => validateExtractionCost(section)).toThrow("fixed corpus");
  const v1Seed = report();
  v1Mixed(v1Seed).effective_seed = "1";
  expect(() => validateExtractionCost(v1Seed)).toThrow("fixed corpus");
  const control = report();
  ladder(control).input[0][0] *= -1;
  expect(() => validateExtractionCost(control)).toThrow("Engineered control input");
  const chain = report();
  v1Chain(chain).input[0][0] *= -1;
  expect(() => validateExtractionCost(chain)).toThrow("Engineered control input");
  const cycle = report();
  v1Contradictory(cycle).input[1] = [1, 2];
  expect(() => validateExtractionCost(cycle)).toThrow("Engineered control input");
  const shape = report();
  mixed(shape).input[mixed(shape).input.length - 1] = [1, 1];
  expect(() => validateExtractionCost(shape)).toThrow("Random clause shape");
  const width = report();
  fragmentOnly(width).input[0] = [1, 2, 3];
  expect(() => validateExtractionCost(width)).toThrow("Random clause shape");
  const ternaryWidth = report();
  v1Ternary(ternaryWidth).input[0] = [1, 2];
  expect(() => validateExtractionCost(ternaryWidth)).toThrow("Random clause shape");
  const counts = report();
  mixed(counts).fragment_clauses++;
  expect(() => validateExtractionCost(counts)).toThrow("Clause or used-variable counts");
  const corpus = report();
  corpus.corpus.primary_families["random-mixed"] = 145;
  expect(() => validateExtractionCost(corpus)).toThrow("Unexpected extraction-cost corpus");
  const arms = report();
  arms.arms.settled = "a linear-time extraction";
  expect(() => validateExtractionCost(arms)).toThrow("arm declaration");
  const declaration = report();
  declaration.comparison.totals = "every case";
  expect(() => validateExtractionCost(declaration)).toThrow("comparison declaration");
  const encoding = report();
  encoding.encoding.vertex_labels = "changed";
  expect(() => validateExtractionCost(encoding)).toThrow("encoding declaration");
  const reproduces = report();
  reproduces.secondary.arm2_reproduces_v1 = false;
  expect(() => validateExtractionCost(reproduces)).toThrow("arm 2 reproduced");
  const extra = report();
  extra.speedup_claim = true;
  expect(() => validateExtractionCost(extra)).toThrow("Unexpected extraction-cost report fields");
  const extraRow = report();
  mixed(extraRow).linear = true;
  expect(() => validateExtractionCost(extraRow)).toThrow("Unexpected observation fields");
});

test("numeric consistency rejects invented gains, omitted work, wrong answers, unexhausted unknowns and altered subtotals", () => {
  const gain = report();
  gain.primary.summary.comparisons.settled_vs_baseline.left_better++;
  expect(() => validateExtractionCost(gain)).toThrow("primary summary differs");
  const extractionGain = report();
  extractionGain.primary.summary.comparisons.extraction_settled_vs_per_literal.settled_better++;
  extractionGain.primary.summary.comparisons.extraction_settled_vs_per_literal.settled_worse--;
  expect(() => validateExtractionCost(extractionGain)).toThrow("primary summary differs");
  const secondaryGain = report();
  secondaryGain.secondary.summary.comparisons.settled_vs_per_literal.left_better++;
  expect(() => validateExtractionCost(secondaryGain)).toThrow("secondary summary differs");
  const perLiteralGain = report();
  perLiteralGain.primary.summary.comparisons.per_literal_vs_baseline.left_worse--;
  expect(() => validateExtractionCost(perLiteralGain)).toThrow("primary summary differs");
  const ratio = report();
  ratio.primary.summary.enumeration_ratio.reference_over_settled = 9.999;
  expect(() => validateExtractionCost(ratio)).toThrow("primary summary differs");
  const searches = report();
  searches.primary.summary.searches.settled--;
  expect(() => validateExtractionCost(searches)).toThrow("primary summary differs");
  const stats = report();
  stats.secondary.summary.settled_stats.inherited++;
  expect(() => validateExtractionCost(stats)).toThrow("secondary summary differs");
  const family = report();
  family.primary.families["ladder-control"].arms.settled.total_work_units--;
  expect(() => validateExtractionCost(family)).toThrow("primary family summary differs");
  const v1Family = report();
  v1Family.secondary.families["v1:random-mixed"].arms.per_literal.phases.extraction_work_units--;
  expect(() => validateExtractionCost(v1Family)).toThrow("secondary family summary differs");
  const binary = report();
  binary.primary.random_mixed_by_binary_count["b=3n"].arms.settled.phases.append_work_units--;
  expect(() => validateExtractionCost(binary)).toThrow("primary binary-count summary differs");
  const v1Binary = report();
  v1Binary.secondary.v1_random_mixed_by_binary_count["b=n/2"].cases--;
  expect(() => validateExtractionCost(v1Binary)).toThrow("secondary binary-count summary differs");
  const group = report();
  group.primary.random_mixed_by_binary_count["b=5n"] = group.primary.random_mixed_by_binary_count["b=4n"];
  expect(() => validateExtractionCost(group)).toThrow("Unexpected primary binary-count summaries fields");
  const familySize = report();
  familySize.primary.families["fragment-only"] = familySize.primary.families["ladder-control"];
  expect(() => validateExtractionCost(familySize)).toThrow("primary family summary differs");
  const work = report();
  work.observations[0].settled.phases.extraction.work_units--;
  expect(() => validateExtractionCost(work)).toThrow("categories do not sum");
  const phase = report();
  phase.observations[0].settled.fragment_work_units--;
  expect(() => validateExtractionCost(phase)).toThrow("settled phase totals");
  const perLiteralPhase = report();
  perLiteralPhase.observations[0].per_literal.total_work_units++;
  expect(() => validateExtractionCost(perLiteralPhase)).toThrow("per_literal phase totals");
  const baselineTotal = report();
  baselineTotal.observations[0].baseline.total_work_units++;
  expect(() => validateExtractionCost(baselineTotal)).toThrow("Baseline totals");
  const answer = report();
  answer.observations[0].baseline.outcome = answer.observations[0].reference.sat ? "unsat" : "sat";
  expect(() => validateExtractionCost(answer)).toThrow("disagrees");
  const settledAnswer = report();
  settledAnswer.observations[0].settled.outcome = settledAnswer.observations[0].reference.sat ? "unsat" : "sat";
  expect(() => validateExtractionCost(settledAnswer)).toThrow("settled decision disagrees");
  const perLiteralAnswer = report();
  perLiteralAnswer.observations[0].per_literal.outcome = perLiteralAnswer.observations[0].reference.sat ? "unsat" : "sat";
  expect(() => validateExtractionCost(perLiteralAnswer)).toThrow("per_literal decision disagrees");
  const unknown = report();
  unknown.observations[0].baseline.outcome = "unknown-budget";
  expect(() => validateExtractionCost(unknown)).toThrow("exhausted work budget");
  const settledUnknown = report();
  settledUnknown.observations[0].settled.outcome = "unknown-budget";
  expect(() => validateExtractionCost(settledUnknown)).toThrow("exhausted work budget");
  const perLiteralUnknown = report();
  perLiteralUnknown.observations[0].per_literal.outcome = "unknown-budget";
  expect(() => validateExtractionCost(perLiteralUnknown)).toThrow("exhausted work budget");
  const coverage = report();
  coverage.observations[0].reference.work.assignments--;
  expect(() => validateExtractionCost(coverage)).toThrow();
  const outside = report();
  outside.outside_arms.checker_work_units--;
  expect(() => validateExtractionCost(outside)).toThrow("Outside-arm totals");
  const overflow = report();
  overflow.observations[0].checks.settled.work.work_units = Number.MAX_SAFE_INTEGER + 1;
  expect(() => validateExtractionCost(overflow)).toThrow("safe event count");
});

test("certificates, clue paths, derived units, arm identity, ladders, settled stats and checker counters are re-checked", () => {
  const values = report();
  sat(values).settled.certificate.values = sat(values).settled.certificate.values.slice(1);
  expect(() => validateExtractionCost(values)).toThrow("one Boolean per declared variable");
  const falsified = report();
  const target = mixed(falsified);
  target.input[target.input.length - 1] = [target.per_literal.certificate.values[0] ? -1 : 1, target.per_literal.certificate.values[1] ? -2 : 2];
  expect(() => validateExtractionCost(falsified)).toThrow("does not satisfy every width-at-most-two clause");
  const path = report();
  withClues(path).settled.clues[0].path.clauses.pop();
  expect(() => validateExtractionCost(path)).toThrow("one clause per edge");
  const edge = report();
  const clue = withClues(edge).per_literal.clues[0];
  clue.path.clauses[0] = (clue.path.clauses[0] + 1) % withClues(edge).input.length;
  expect(() => validateExtractionCost(edge)).toThrow();
  const wide = report();
  const cited = withClues(wide);
  cited.settled.clues[0].path.clauses[0] = cited.input.findIndex(raw => raw.length === 3);
  expect(() => validateExtractionCost(wide)).toThrow("does not support");
  const endpoints = report();
  withClues(endpoints).settled.clues[0].literal *= -1;
  expect(() => validateExtractionCost(endpoints)).toThrow();
  const opposite = report();
  withPaths(opposite).settled.certificate.positive_to_negative.nodes.reverse();
  expect(() => validateExtractionCost(opposite)).toThrow("endpoints");
  const order = report();
  withClues(order).settled.derived_units.reverse();
  expect(() => validateExtractionCost(order)).toThrow("clue literals in order");
  const backbone = report();
  const forced = satWithClues(backbone);
  forced.reference.backbone = forced.reference.backbone.filter(unit => unit !== forced.settled.derived_units[0]);
  expect(() => validateExtractionCost(backbone)).toThrow("subset of the reference backbone");
  const unequal = report();
  const differing = withClues(unequal);
  differing.settled.clues.pop();
  differing.settled.derived_units.pop();
  expect(() => validateExtractionCost(unequal)).toThrow("derived different units");
  const certificateIdentity = report();
  const flipped = mixed(certificateIdentity);
  flipped.settled.certificate = { kind: "sat", values: flipped.settled.certificate.values.map(value => !value) };
  expect(() => validateExtractionCost(certificateIdentity)).toThrow();
  const shared = report();
  const drift = mixed(shared);
  drift.settled.phases.components.literal_reads++;
  drift.settled.phases.components.work_units++;
  drift.settled.fragment_work_units++;
  drift.settled.total_work_units++;
  expect(() => validateExtractionCost(shared)).toThrow("differ outside the extraction phase");
  const rung = report();
  const incomplete = ladder(rung);
  incomplete.per_literal.clues.pop();
  incomplete.per_literal.derived_units.pop();
  expect(() => validateExtractionCost(rung)).toThrow("exactly the j ladder literals");
  const chained = report();
  v1Chain(chained).settled.clues = [];
  v1Chain(chained).settled.derived_units = [];
  expect(() => validateExtractionCost(chained)).toThrow("exactly the selected sign");
  const emptyFragment = report();
  v1Ternary(emptyFragment).per_literal.derived_units = [1];
  expect(() => validateExtractionCost(emptyFragment)).toThrow();
  const residual = report();
  v1Ternary(residual).settled.phases.residual.formula_checks++;
  v1Ternary(residual).settled.phases.residual.clause_reads--;
  expect(() => validateExtractionCost(residual)).toThrow("residual counters on an empty fragment");
  const refuted = report();
  const cycle = v1Contradictory(refuted);
  for (const key of ["work_units", "clause_reads"]) cycle.per_literal.phases.residual[key] = 5;
  cycle.per_literal.residual_work_units = 5;
  cycle.per_literal.total_work_units += 5;
  expect(() => validateExtractionCost(refuted)).toThrow("without extraction, appends, or residual work");
  const visited = report();
  withStats(visited).settled_stats.vertices_visited++;
  expect(() => validateExtractionCost(visited)).toThrow("searches plus search nodes");
  const tooManySearches = report();
  const crowded = withStats(tooManySearches);
  crowded.settled_stats.inherited = 2 * crowded.variables;
  expect(() => validateExtractionCost(tooManySearches)).toThrow("exceed the vertex count");
  const statsOnUnsat = report();
  withPaths(statsOnUnsat).settled_stats = { searches: 0, inherited: 0, settled_good: 0, vertices_visited: 0 };
  expect(() => validateExtractionCost(statsOnUnsat)).toThrow("require a completed settled extraction");
  const statsMissing = report();
  withStats(statsMissing).settled_stats = null;
  expect(() => validateExtractionCost(statsMissing)).toThrow("Unexpected settled stats fields");
  const unsatBackbone = report();
  unsat(unsatBackbone).reference.backbone = [];
  expect(() => validateExtractionCost(unsatBackbone)).toThrow("UNSAT reference");
  const nullBackbone = report();
  sat(nullBackbone).reference.backbone = null;
  expect(() => validateExtractionCost(nullBackbone)).toThrow("distinct forced literals");
  const checker = report();
  withClues(checker).checks.settled.clues_valid--;
  expect(() => validateExtractionCost(checker)).toThrow("settled checker outcome");
  const certificate = report();
  withPaths(certificate).checks.per_literal.certificate_valid = false;
  expect(() => validateExtractionCost(certificate)).toThrow("per_literal checker outcome");
});

test("local ingestion is additive, repeatable, and records both sections, the comparisons and settled stats without a speedup proposition", () => {
  const path = root();
  initializeLedger(path);
  const first = recordExtractionCost(path, "artifacts/extraction-cost.json");
  const second = recordExtractionCost(path, "artifacts/extraction-cost.json");
  expect(second.inserted).toBe(0);
  expect(second.verification).toEqual(first.verification);
  const oh = openLedger(path);
  try {
    // The 1.78 MB canonical report exceeds the pinned runtime's 1 MiB record
    // bound, so the edition stores it as ordered observation parts that
    // reassemble to the exact report; the five-record pattern gains one
    // edition per part.
    const edition = oh.get("edition:extraction-cost-" + first.reportSha256);
    expect(edition.value.report.observations).toBeUndefined();
    expect(edition.value.observationCount).toBe(338);
    const parts = edition.value.observationParts;
    expect(parts.length).toBeGreaterThan(1);
    expect(edition.dependencies).toEqual(parts);
    expect(first.inserted).toBe(5 + parts.length);
    expect(first.verification.records).toBe(11 + parts.length);
    const assembled = editionReport(edition, key => oh.get(key));
    expect(canonicalJson(assembled)).toBe(canonicalJson(report()));
    for (const [index, key] of parts.entries()) {
      const part = oh.get(key).value;
      expect([part.part, part.parts, part.reportSha256, part.path]).toEqual([index, parts.length, first.reportSha256, "artifacts/extraction-cost.json"]);
      expect(Buffer.byteLength(canonicalJson(part), "utf8")).toBeLessThan(1024 * 1024);
    }
    expect(() => editionReport(edition, key => key === parts[1] ? oh.get(parts[0]) : oh.get(key))).toThrow("inconsistent with its edition");
    expect(() => editionReport(edition, key => key === parts[0] ? null : oh.get(key))).toThrow("missing");
    const observation = oh.list({ kind: "assertion", limit: 20 }).find(record => record.key.startsWith("assertion:extraction-cost-"));
    expect(observation.value.stance).toBe("bounded-observation");
    expect(observation.value.formalProofAccepted).toBe(false);
    expect(observation.value.statement).toBe("statement:extraction-cost-v1-comparison");
    const statement = oh.get("statement:extraction-cost-v1-comparison").value;
    expect(statement.proposition).toContain("three arms");
    expect(statement.domain).toContain("no total-work improvement");
    expect(oh.get("edition:extraction-cost-" + first.reportSha256).value.path).toBe("artifacts/extraction-cost.json");
    const evidence = oh.list({ kind: "evidence", limit: 20 }).find(record => record.key.startsWith("evidence:extraction-cost-"));
    const actual = report();
    expect(evidence.value.kind).toBe("finite-extraction-cost-report");
    expect(evidence.value.measuredSummary).toEqual({ primary: actual.primary.summary, secondary: actual.secondary.summary });
    expect(evidence.value.comparison).toEqual(actual.comparison);
    expect(Object.keys(evidence.value.comparisons.primary).sort()).toEqual(["extraction_settled_vs_per_literal", "per_literal_vs_baseline", "settled_vs_baseline", "settled_vs_per_literal"]);
    expect(evidence.value.comparisons.secondary).toEqual(actual.secondary.summary.comparisons);
    expect(evidence.value.extractionWorkUnits.primary).toEqual({
      per_literal: actual.primary.summary.arms.per_literal.phases.extraction_work_units,
      settled: actual.primary.summary.arms.settled.phases.extraction_work_units,
    });
    expect(evidence.value.settledStats.secondary).toEqual(actual.secondary.summary.settled_stats);
    expect(evidence.value.outsideArmWorkUnits).toEqual(actual.outside_arms);
    expect(evidence.value.enumerationRatios.primary).toEqual(actual.primary.summary.enumeration_ratio);
    expect(evidence.value.limitations).toEqual(actual.limitations);
    expect(evidence.value.frozenLibrarySha256).toBeUndefined();
    expect(evidence.value.formalProofAccepted).toBe(false);
    expect(oh.get("assertion:p-equals-np-hypothesis").value.stance).toBe("research-hypothesis");
  } finally { oh.store.close(); }
}, 120_000);

test("invalid report and changed protocol fail before initializing or changing research state", () => {
  const path = root();
  const wrong = report();
  wrong.primary.summary.arms.settled.derived_units++;
  writeFileSync(join(path, "artifacts/extraction-cost.json"), JSON.stringify(wrong));
  expect(() => recordExtractionCost(path, "artifacts/extraction-cost.json")).toThrow("primary summary differs");
  expect(existsSync(join(path, ".oh"))).toBe(false);
  writeFileSync(join(path, "artifacts/extraction-cost.json"), reportBytes);
  const initial = initializeLedger(path);
  writeFileSync(join(path, "experiments/extraction-cost-protocol.md"), "changed protocol\n");
  expect(() => recordExtractionCost(path, "artifacts/extraction-cost.json")).toThrow("fixed protocol identity");
  const oh = openLedger(path);
  expect(oh.verify()).toEqual(initial.verification);
  oh.store.close();
}, 120_000);
