import { afterEach, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initializeLedger, openLedger } from "./oh-ledger.mjs";
import { recordFragmentInterface } from "./oh-experiment-records.mjs";
import { FRAGMENT_PROTOCOL_SHA256, validateFragmentInterface } from "./oh-fragment-report.mjs";

const roots = [];
const reportBytes = readFileSync(new URL("../artifacts/fragment-interface.json", import.meta.url));
const protocolBytes = readFileSync(new URL("../experiments/fragment-interface-protocol.md", import.meta.url));
const report = () => JSON.parse(reportBytes);
function root() {
  const path = mkdtempSync(join(tmpdir(), "peqnp-fragment-ledger-test-"));
  roots.push(path);
  for (const directory of ["artifacts", "experiments", "src"]) mkdirSync(join(path, directory));
  for (const file of ["Cargo.toml", "Cargo.lock", "rust-toolchain.toml"]) writeFileSync(join(path, file), "# synthetic source fixture\n");
  writeFileSync(join(path, "src/lib.rs"), "// Synthetic source fixture, not experimental provenance.\n");
  writeFileSync(join(path, "artifacts/fragment-interface.json"), reportBytes);
  writeFileSync(join(path, "experiments/fragment-interface-protocol.md"), protocolBytes);
  return path;
}
afterEach(() => { for (const path of roots.splice(0)) rmSync(path, { recursive: true, force: true }); });
const find = (actual, predicate) => actual.observations.find(predicate);
const withClues = actual => find(actual, row => row.fragment.clues.length > 0);
const withPaths = actual => find(actual, row => row.fragment.certificate?.kind === "opposite-paths");
const unsat = actual => find(actual, row => !row.reference.sat);
const sat = actual => find(actual, row => row.reference.sat);
const satWithClues = actual => find(actual, row => row.reference.sat && row.fragment.clues.length > 0);
const mixed = actual => find(actual, row => row.family === "random-mixed" && row.fragment.certificate?.kind === "sat");
const ternary = actual => find(actual, row => row.family === "random-ternary-only");
const chain = actual => find(actual, row => row.family === "chain-embedded");
const contradictory = actual => find(actual, row => row.family === "contradictory-fragment");

test("fragment report preserves the fixed corpus and rejects proof, protocol, and corpus changes", () => {
  const actual = report();
  expect(actual.protocol_sha256).toBe(FRAGMENT_PROTOCOL_SHA256);
  expect(validateFragmentInterface(actual)).toBe(actual);
  const proof = report();
  proof.proof_status = "proved-generally";
  expect(() => validateFragmentInterface(proof)).toThrow("without a formal-proof");
  const protocol = report();
  protocol.protocol_sha256 = "0".repeat(64);
  expect(() => validateFragmentInterface(protocol)).toThrow("without a formal-proof");
  const missing = report();
  missing.observations.pop();
  expect(() => validateFragmentInterface(missing)).toThrow("every fixed fragment-interface case");
  const duplicate = report();
  duplicate.observations[1] = duplicate.observations[0];
  expect(() => validateFragmentInterface(duplicate)).toThrow("duplicate");
  const renamed = report();
  mixed(renamed).density = 6;
  expect(() => validateFragmentInterface(renamed)).toThrow("fixed corpus");
  const seed = report();
  mixed(seed).effective_seed = "1";
  expect(() => validateFragmentInterface(seed)).toThrow("fixed corpus");
  const control = report();
  chain(control).input[0][0] *= -1;
  expect(() => validateFragmentInterface(control)).toThrow("Engineered control input");
  const cycle = report();
  contradictory(cycle).input[1] = [1, 2];
  expect(() => validateFragmentInterface(cycle)).toThrow("Engineered control input");
  const shape = report();
  mixed(shape).input[mixed(shape).input.length - 1] = [1, 1];
  expect(() => validateFragmentInterface(shape)).toThrow("Random clause shape");
  const width = report();
  ternary(width).input[0] = [1, 2];
  expect(() => validateFragmentInterface(width)).toThrow("Random clause shape");
  const counts = report();
  mixed(counts).fragment_clauses++;
  expect(() => validateFragmentInterface(counts)).toThrow("Clause or used-variable counts");
  const corpus = report();
  corpus.corpus.families["random-mixed"] = 109;
  expect(() => validateFragmentInterface(corpus)).toThrow("Unexpected fragment-interface corpus");
  const declaration = report();
  declaration.comparison.restricted_to = "every case";
  expect(() => validateFragmentInterface(declaration)).toThrow("comparison declaration");
  const extra = report();
  extra.speedup_claim = true;
  expect(() => validateFragmentInterface(extra)).toThrow("Unexpected fragment-interface report fields");
});

test("numeric consistency rejects invented gains, omitted work, wrong answers, unexhausted unknowns and altered subtotals", () => {
  const gain = report();
  gain.summary.comparisons.fragment_vs_baseline.left_better++;
  expect(() => validateFragmentInterface(gain)).toThrow("Summary differs");
  const ratio = report();
  ratio.summary.enumeration_ratio.reference_over_fragment = 9.999;
  expect(() => validateFragmentInterface(ratio)).toThrow("Summary differs");
  const family = report();
  family.families["random-mixed"].arms.fragment.total_work_units--;
  expect(() => validateFragmentInterface(family)).toThrow("family summary differs");
  const binary = report();
  binary.random_mixed_by_binary_count["b=n"].arms.fragment.phases.append_work_units--;
  expect(() => validateFragmentInterface(binary)).toThrow("binary-count summary differs");
  const variables = report();
  variables.random_by_variables["n=8"].cases--;
  expect(() => validateFragmentInterface(variables)).toThrow("random-variables summary differs");
  const density = report();
  density.random_by_density["t=5"].arms.baseline.search_nodes++;
  expect(() => validateFragmentInterface(density)).toThrow("random-density summary differs");
  const group = report();
  group.random_by_density["t=6"] = group.random_by_density["t=5"];
  expect(() => validateFragmentInterface(group)).toThrow("Unexpected random-density summaries fields");
  const work = report();
  work.observations[0].fragment.phases.components.work_units--;
  expect(() => validateFragmentInterface(work)).toThrow("categories do not sum");
  const phase = report();
  phase.observations[0].fragment.fragment_work_units--;
  expect(() => validateFragmentInterface(phase)).toThrow("phase totals");
  const baselineTotal = report();
  baselineTotal.observations[0].baseline.total_work_units++;
  expect(() => validateFragmentInterface(baselineTotal)).toThrow("Baseline totals");
  const answer = report();
  answer.observations[0].baseline.outcome = answer.observations[0].reference.sat ? "unsat" : "sat";
  expect(() => validateFragmentInterface(answer)).toThrow("disagrees");
  const fragmentAnswer = report();
  fragmentAnswer.observations[0].fragment.outcome = fragmentAnswer.observations[0].reference.sat ? "unsat" : "sat";
  expect(() => validateFragmentInterface(fragmentAnswer)).toThrow("Fragment decision disagrees");
  const unknown = report();
  unknown.observations[0].baseline.outcome = "unknown-budget";
  expect(() => validateFragmentInterface(unknown)).toThrow("exhausted work budget");
  const fragmentUnknown = report();
  fragmentUnknown.observations[0].fragment.outcome = "unknown-budget";
  expect(() => validateFragmentInterface(fragmentUnknown)).toThrow("exhausted work budget");
  const coverage = report();
  coverage.observations[0].reference.work.assignments--;
  expect(() => validateFragmentInterface(coverage)).toThrow();
  const outside = report();
  outside.outside_arms.reference_work_units--;
  expect(() => validateFragmentInterface(outside)).toThrow("Outside-arm totals");
  const overflow = report();
  overflow.observations[0].checks.work.work_units = Number.MAX_SAFE_INTEGER + 1;
  expect(() => validateFragmentInterface(overflow)).toThrow("safe event count");
});

test("certificates, clue paths, derived units, controls and checker counters are re-checked against the raw clauses", () => {
  const values = report();
  sat(values).fragment.certificate.values = sat(values).fragment.certificate.values.slice(1);
  expect(() => validateFragmentInterface(values)).toThrow("one Boolean per declared variable");
  const falsified = report();
  const target = mixed(falsified);
  target.input[target.input.length - 1] = [target.fragment.certificate.values[0] ? -1 : 1, target.fragment.certificate.values[1] ? -2 : 2];
  expect(() => validateFragmentInterface(falsified)).toThrow("does not satisfy every width-at-most-two clause");
  const path = report();
  withClues(path).fragment.clues[0].path.clauses.pop();
  expect(() => validateFragmentInterface(path)).toThrow("one clause per edge");
  const edge = report();
  const clue = withClues(edge).fragment.clues[0];
  clue.path.clauses[0] = (clue.path.clauses[0] + 1) % withClues(edge).input.length;
  expect(() => validateFragmentInterface(edge)).toThrow();
  const wide = report();
  const cited = withClues(wide);
  cited.fragment.clues[0].path.clauses[0] = cited.input.findIndex(raw => raw.length === 3);
  expect(() => validateFragmentInterface(wide)).toThrow("does not support");
  const endpoints = report();
  withClues(endpoints).fragment.clues[0].literal *= -1;
  expect(() => validateFragmentInterface(endpoints)).toThrow();
  const opposite = report();
  withPaths(opposite).fragment.certificate.positive_to_negative.nodes.reverse();
  expect(() => validateFragmentInterface(opposite)).toThrow("endpoints");
  const order = report();
  const ordered = find(order, row => row.fragment.clues.length > 1);
  ordered.fragment.derived_units.reverse();
  expect(() => validateFragmentInterface(order)).toThrow("clue literals in order");
  const backbone = report();
  const forced = satWithClues(backbone);
  forced.reference.backbone = forced.reference.backbone.filter(unit => unit !== forced.fragment.derived_units[0]);
  expect(() => validateFragmentInterface(backbone)).toThrow("subset of the reference backbone");
  const emptyFragment = report();
  ternary(emptyFragment).fragment.derived_units = [1];
  expect(() => validateFragmentInterface(emptyFragment)).toThrow();
  const residual = report();
  ternary(residual).fragment.phases.residual.formula_checks++;
  ternary(residual).fragment.phases.residual.clause_reads--;
  expect(() => validateFragmentInterface(residual)).toThrow("Residual counters on an empty fragment");
  const refuted = report();
  const cycle = contradictory(refuted);
  for (const key of ["work_units", "clause_reads"]) cycle.fragment.phases.residual[key] = 5;
  cycle.fragment.residual_work_units = 5;
  cycle.fragment.total_work_units += 5;
  expect(() => validateFragmentInterface(refuted)).toThrow("without extraction, appends, or residual work");
  const chained = report();
  chain(chained).fragment.clues = [];
  chain(chained).fragment.derived_units = [];
  expect(() => validateFragmentInterface(chained)).toThrow("derive exactly the selected sign");
  const unsatBackbone = report();
  unsat(unsatBackbone).reference.backbone = [];
  expect(() => validateFragmentInterface(unsatBackbone)).toThrow("UNSAT reference");
  const nullBackbone = report();
  sat(nullBackbone).reference.backbone = null;
  expect(() => validateFragmentInterface(nullBackbone)).toThrow("distinct forced literals");
  const checker = report();
  withClues(checker).checks.clues_valid--;
  expect(() => validateFragmentInterface(checker)).toThrow("Checker outcome");
  const certificate = report();
  withPaths(certificate).checks.certificate_valid = false;
  expect(() => validateFragmentInterface(certificate)).toThrow("Checker outcome");
});

test("local ingestion is additive, repeatable, and records phases, ratios and the comparison without a speedup proposition", () => {
  const path = root();
  initializeLedger(path);
  const first = recordFragmentInterface(path, "artifacts/fragment-interface.json");
  expect(first.inserted).toBe(5);
  expect(first.verification.records).toBe(11);
  const second = recordFragmentInterface(path, "artifacts/fragment-interface.json");
  expect(second.inserted).toBe(0);
  expect(second.verification).toEqual(first.verification);
  const oh = openLedger(path);
  try {
    const observation = oh.list({ kind: "assertion", limit: 20 }).find(record => record.key.startsWith("assertion:fragment-interface-"));
    expect(observation.value.stance).toBe("bounded-observation");
    expect(observation.value.formalProofAccepted).toBe(false);
    expect(observation.value.statement).toBe("statement:fragment-interface-v1-comparison");
    expect(oh.get("statement:fragment-interface-v1-comparison").value.domain).toContain("no total-work improvement");
    expect(oh.get("edition:fragment-interface-" + first.reportSha256).value.path).toBe("artifacts/fragment-interface.json");
    const evidence = oh.list({ kind: "evidence", limit: 20 }).find(record => record.key.startsWith("evidence:fragment-interface-"));
    expect(evidence.value.kind).toBe("finite-fragment-interface-report");
    expect(evidence.value.measuredSummary).toEqual(report().summary);
    expect(evidence.value.comparison).toEqual(report().comparison);
    expect(evidence.value.phaseWorkUnits).toEqual(report().summary.arms.fragment.phases);
    expect(evidence.value.outsideArmWorkUnits).toEqual(report().outside_arms);
    expect(evidence.value.enumerationRatios).toEqual(report().summary.enumeration_ratio);
    expect(evidence.value.limitations).toEqual(report().limitations);
    expect(evidence.value.frozenLibrarySha256).toBeUndefined();
    expect(evidence.value.formalProofAccepted).toBe(false);
    expect(oh.get("assertion:p-equals-np-hypothesis").value.stance).toBe("research-hypothesis");
  } finally { oh.store.close(); }
});

test("invalid report and changed protocol fail before initializing or changing research state", () => {
  const path = root();
  const wrong = report();
  wrong.summary.arms.fragment.derived_units++;
  writeFileSync(join(path, "artifacts/fragment-interface.json"), JSON.stringify(wrong));
  expect(() => recordFragmentInterface(path, "artifacts/fragment-interface.json")).toThrow("Summary differs");
  expect(existsSync(join(path, ".oh"))).toBe(false);
  writeFileSync(join(path, "artifacts/fragment-interface.json"), reportBytes);
  const initial = initializeLedger(path);
  writeFileSync(join(path, "experiments/fragment-interface-protocol.md"), "changed protocol\n");
  expect(() => recordFragmentInterface(path, "artifacts/fragment-interface.json")).toThrow("fixed protocol identity");
  const oh = openLedger(path);
  expect(oh.verify()).toEqual(initial.verification);
  oh.store.close();
});
