import { afterEach, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalSha256 } from "@hraness/oh";
import { initializeLedger, openLedger } from "./oh-ledger.mjs";
import { recordImplicationCalibration } from "./oh-experiment-records.mjs";
import { IMPLICATION_PROTOCOL_SHA256, validateImplicationCalibration } from "./oh-implication-report.mjs";

const roots = [];
const reportBytes = readFileSync(new URL("../artifacts/implication-calibration.json", import.meta.url));
const protocolBytes = readFileSync(new URL("../experiments/implication-protocol.md", import.meta.url));
const report = () => JSON.parse(reportBytes);
function root() {
  const path = mkdtempSync(join(tmpdir(), "peqnp-implication-ledger-test-"));
  roots.push(path);
  for (const directory of ["artifacts", "experiments", "src"]) mkdirSync(join(path, directory));
  for (const file of ["Cargo.toml", "Cargo.lock", "rust-toolchain.toml"]) writeFileSync(join(path, file), "# synthetic source fixture\n");
  writeFileSync(join(path, "src/lib.rs"), "// Synthetic source fixture, not experimental provenance.\n");
  writeFileSync(join(path, "artifacts/implication-calibration.json"), reportBytes);
  writeFileSync(join(path, "experiments/implication-protocol.md"), protocolBytes);
  return path;
}
afterEach(() => { for (const path of roots.splice(0)) rmSync(path, { recursive: true, force: true }); });
const find = (actual, predicate) => actual.observations.find(predicate);
const withClues = actual => find(actual, row => row.graph.clues.length > 0);
const withPaths = actual => find(actual, row => row.graph.certificate.kind === "opposite-paths");
const unsat = actual => find(actual, row => !row.reference.sat);
const sat = actual => find(actual, row => row.reference.sat && row.variables > 0);

test("implication report preserves the fixed corpus and rejects proof, protocol, coverage and library changes", () => {
  const actual = report();
  expect(actual.protocol_sha256).toBe(IMPLICATION_PROTOCOL_SHA256);
  expect(validateImplicationCalibration(actual)).toBe(actual);
  const proof = report();
  proof.proof_status = "proved-generally";
  expect(() => validateImplicationCalibration(proof)).toThrow("without a formal-proof");
  const protocol = report();
  protocol.protocol_sha256 = "0".repeat(64);
  expect(() => validateImplicationCalibration(protocol)).toThrow("without a formal-proof");
  const missing = report();
  missing.observations.pop();
  expect(() => validateImplicationCalibration(missing)).toThrow("every fixed calibration case");
  const duplicate = report();
  duplicate.observations[1] = duplicate.observations[0];
  expect(() => validateImplicationCalibration(duplicate)).toThrow("duplicate");
  const renamed = report();
  find(renamed, row => row.family === "random-2cnf").density = 3;
  expect(() => validateImplicationCalibration(renamed)).toThrow("fixed corpus");
  const control = report();
  find(control, row => row.family === "long-explanation").input[0][0] *= -1;
  expect(() => validateImplicationCalibration(control)).toThrow("Engineered control input");
  const expectation = report();
  const chain = find(expectation, row => row.family === "long-explanation");
  chain.reference.backbone = [];
  expect(() => validateImplicationCalibration(expectation)).toThrow("stated expectation");
  const rule = report();
  rule.frozen_library.rules[0].conclusion *= -1;
  expect(() => validateImplicationCalibration(rule)).toThrow("accepted mining rules");
  const corpus = report();
  corpus.corpus.families["random-2cnf"] = 49;
  expect(() => validateImplicationCalibration(corpus)).toThrow("Unexpected implication-calibration corpus");
  const extra = report();
  extra.speedup_claim = true;
  expect(() => validateImplicationCalibration(extra)).toThrow("Unexpected implication-calibration report fields");
});

test("numeric consistency rejects invented gains, omitted work, wrong answers, unexhausted unknowns and coverage inflation", () => {
  const gain = report();
  gain.summary.comparisons.graph_decision_vs_dpll.left_better++;
  expect(() => validateImplicationCalibration(gain)).toThrow("Summary differs");
  const coverage = report();
  coverage.summary.coverage.local.found_literals++;
  expect(() => validateImplicationCalibration(coverage)).toThrow("Summary differs");
  const family = report();
  family.families["random-2cnf"].arms.graph.decision_work_units--;
  expect(() => validateImplicationCalibration(family)).toThrow("Family summary differs");
  const work = report();
  work.observations[0].graph.phases.scc.work_units--;
  expect(() => validateImplicationCalibration(work)).toThrow("categories do not sum");
  const phase = report();
  phase.observations[0].graph.decision_work_units--;
  expect(() => validateImplicationCalibration(phase)).toThrow("phase totals");
  const answer = report();
  answer.observations[0].dpll.outcome = answer.observations[0].reference.sat ? "unsat" : "sat";
  expect(() => validateImplicationCalibration(answer)).toThrow("disagrees");
  const unknown = report();
  unknown.observations[0].dpll.outcome = "unknown-budget";
  expect(() => validateImplicationCalibration(unknown)).toThrow("exhausted work budget");
  const local = report();
  local.observations[0].local.complete = false;
  expect(() => validateImplicationCalibration(local)).toThrow("exhausted budget");
  const outside = report();
  outside.outside_arms.reference_work_units--;
  expect(() => validateImplicationCalibration(outside)).toThrow("Outside-arm totals");
  const overflow = report();
  overflow.setup.acquisition.work_units = Number.MAX_SAFE_INTEGER + 1;
  expect(() => validateImplicationCalibration(overflow)).toThrow("safe event count");
});

test("certificates, clue paths, backbones and checker counters are re-checked against the raw clauses", () => {
  const values = report();
  const row = sat(values);
  row.graph.certificate.values = row.graph.certificate.values.slice(1);
  expect(() => validateImplicationCalibration(values)).toThrow("one Boolean per declared variable");
  const falsified = report();
  const target = sat(falsified);
  target.graph.certificate.values = target.graph.certificate.values.map(() => false);
  target.graph.certificate.values[Math.abs(target.input[0][0]) - 1] = target.input[0][0] < 0;
  target.input[0] = [target.input[0][0]];
  expect(() => validateImplicationCalibration(falsified)).toThrow();
  const path = report();
  withClues(path).graph.clues[0].path.clauses.pop();
  expect(() => validateImplicationCalibration(path)).toThrow("one clause per edge");
  const edge = report();
  const clue = withClues(edge).graph.clues[0];
  clue.path.clauses[0] = (clue.path.clauses[0] + 1) % withClues(edge).input.length;
  expect(() => validateImplicationCalibration(edge)).toThrow();
  const endpoints = report();
  withClues(endpoints).graph.clues[0].literal *= -1;
  expect(() => validateImplicationCalibration(endpoints)).toThrow();
  const opposite = report();
  withPaths(opposite).graph.certificate.positive_to_negative.nodes.reverse();
  expect(() => validateImplicationCalibration(opposite)).toThrow("endpoints");
  const unsatClues = report();
  const contradiction = unsat(unsatClues);
  contradiction.graph.clues = [{ literal: 1, path: { nodes: [-1, 1], clauses: [0] } }];
  expect(() => validateImplicationCalibration(unsatClues)).toThrow("UNSAT rows");
  const status = report();
  unsat(status).graph.backbone_status = "complete";
  expect(() => validateImplicationCalibration(status)).toThrow("UNSAT rows");
  const backbone = report();
  unsat(backbone).reference.backbone = [];
  expect(() => validateImplicationCalibration(backbone)).toThrow("UNSAT reference");
  const nullBackbone = report();
  sat(nullBackbone).reference.backbone = null;
  expect(() => validateImplicationCalibration(nullBackbone)).toThrow("distinct forced literals");
  const incomplete = report();
  withClues(incomplete).graph.clues.pop();
  expect(() => validateImplicationCalibration(incomplete)).toThrow("differs from the reference backbone");
  const checker = report();
  withClues(checker).checks.clues_valid--;
  expect(() => validateImplicationCalibration(checker)).toThrow("Checker outcome");
});

test("local ingestion is additive, repeatable, and records coverage and costs without a speedup proposition", () => {
  const path = root();
  initializeLedger(path);
  const first = recordImplicationCalibration(path, "artifacts/implication-calibration.json");
  expect(first.inserted).toBe(5);
  expect(first.verification.records).toBe(11);
  const second = recordImplicationCalibration(path, "artifacts/implication-calibration.json");
  expect(second.inserted).toBe(0);
  expect(second.verification).toEqual(first.verification);
  const oh = openLedger(path);
  try {
    const observation = oh.list({ kind: "assertion", limit: 20 }).find(record => record.key.startsWith("assertion:implication-calibration-"));
    expect(observation.value.stance).toBe("bounded-observation");
    expect(observation.value.formalProofAccepted).toBe(false);
    expect(observation.value.statement).toBe("statement:implication-calibration-v1-comparison");
    expect(oh.get("statement:implication-calibration-v1-comparison").value.domain).toContain("no speedup");
    expect(oh.get("edition:implication-calibration-" + first.reportSha256).value.path).toBe("artifacts/implication-calibration.json");
    const evidence = oh.list({ kind: "evidence", limit: 20 }).find(record => record.key.startsWith("evidence:implication-calibration-"));
    expect(evidence.value.kind).toBe("finite-implication-calibration-report");
    expect(evidence.value.measuredSummary).toEqual(report().summary);
    expect(evidence.value.coverage).toEqual(report().summary.coverage);
    expect(evidence.value.decisionComparison).toEqual(report().decision_comparison);
    expect(evidence.value.outsideArmWorkUnits).toEqual(report().outside_arms);
    expect(evidence.value.frozenLibrarySha256).toBe(canonicalSha256(report().frozen_library.rules));
    expect(evidence.value.formalProofAccepted).toBe(false);
    expect(oh.get("assertion:p-equals-np-hypothesis").value.stance).toBe("research-hypothesis");
  } finally { oh.store.close(); }
});

test("invalid report and changed protocol fail before initializing or changing research state", () => {
  const path = root();
  const wrong = report();
  wrong.summary.arms.graph.clues++;
  writeFileSync(join(path, "artifacts/implication-calibration.json"), JSON.stringify(wrong));
  expect(() => recordImplicationCalibration(path, "artifacts/implication-calibration.json")).toThrow("Summary differs");
  expect(existsSync(join(path, ".oh"))).toBe(false);
  writeFileSync(join(path, "artifacts/implication-calibration.json"), reportBytes);
  const initial = initializeLedger(path);
  writeFileSync(join(path, "experiments/implication-protocol.md"), "changed protocol\n");
  expect(() => recordImplicationCalibration(path, "artifacts/implication-calibration.json")).toThrow("fixed protocol identity");
  const oh = openLedger(path);
  expect(oh.verify()).toEqual(initial.verification);
  oh.store.close();
});
